sudo: enabled

language: python
python:
    - "3.6"

install:
    - pip install -r requirements.txt

script:
    - mkdir log
    - touch ./log/movie_rating.log
    - pytest -v  ./tests/test_movie_rating.py

